name: Android Build CI (Fast)

on: [workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-${{ matrix.version }}
    strategy:
      matrix:
        version: [20.04, 22.04]
        build: [release, debug]
        arch: [arm64, armv7, 32]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: zulu
          java-version: 12
      - name: Setup Android SDK
        uses: android-actions/setup-android@main
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0 --quiet
          haxelib git hxcpp https://github.com/mcagabe19/hxcpp-fastspeed > /dev/null
          haxelib install openfl 9.1.0 --quiet
          haxelib install actuate --quiet
          haxelib --never git flixel https://github.com/mcagabe19/flixel-4.11.0.git
          haxelib install flixel-ui --quiet
          haxelib install hscript --quiet
          haxelib install flixel-addons --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
          haxelib git polymod https://github.com/mcagabe19/polymod-for-steve.git
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git
          haxelib git extension-videoview https://github.com/MAJigsaw77/extension-videoview.git
          haxelib set openfl 9.1.0
          haxelib set lime 7.9.0
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Compile
        run: haxelib run lime build android -${{ matrix.build }} -D no-compilation -D luajit_static -D macro-times -D analyzer-optimize -${{ matrix.arch }} --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build-ubuntu${{ matrix.version }}-${{ matrix.arch }}-${{ matrix.build }}
          path: 'export/${{ matrix.build }}/android/bin/app/build/outputs/apk/debug/*.apk'
  build-armv6:
    name: Build ArmV6
    runs-on: ubuntu-${{ matrix.version }}
    strategy:
      matrix:
        version: [20.04, 22.04]
        build: [release, debug]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r11c
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: zulu
          java-version: 12
      - name: Setup Android SDK
        uses: android-actions/setup-android@main
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0 --quiet
          haxelib git hxcpp https://github.com/mcagabe19/hxcpp-fastspeed > /dev/null
          haxelib install openfl 9.1.0 --quiet
          haxelib install actuate --quiet
          haxelib --never git flixel https://github.com/mcagabe19/flixel-4.11.0.git
          haxelib install flixel-ui --quiet
          haxelib install hscript --quiet
          haxelib install flixel-addons --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git polymod https://github.com/mcagabe19/polymod-for-steve.git
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git
          haxelib git extension-videoview https://github.com/MAJigsaw77/extension-videoview.git
          haxelib set openfl 9.1.0
          haxelib set lime 7.9.0
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Compile
        run: haxelib run lime build android -armv6 -${{ matrix.build }} -D nolua -D no-compilation -D macro-times -D analyzer-optimize -${{ matrix.arch }} --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build-ubuntu${{ matrix.version }}-armv6-${{ matrix.build }}
          path: 'export/${{ matrix.build }}/android/bin/app/build/outputs/apk/debug/*.apk'
  build-8664:
    name: Build X86_64
    runs-on: ubuntu-${{ matrix.version }}
    strategy:
      matrix:
        version: [20.04, 22.04]
        build: [release, debug]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r21e
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: zulu
          java-version: 12
      - name: Setup Android SDK
        uses: android-actions/setup-android@main
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib git lime https://github.com/mcagabe19/lime --quiet
          haxelib git hxcpp https://github.com/mcagabe19/hxcpp-fastspeed > /dev/null
          haxelib install openfl 9.1.0 --quiet
          haxelib install actuate --quiet
          haxelib --never git flixel https://github.com/mcagabe19/flixel-4.11.0.git
          haxelib install flixel-ui --quiet
          haxelib install hscript --quiet
          haxelib install flixel-addons --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
          haxelib git polymod https://github.com/mcagabe19/polymod-for-steve.git
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git
          haxelib git extension-videoview https://github.com/MAJigsaw77/extension-videoview.git
          haxelib set openfl 9.1.0
          haxelib set lime 7.9.0
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Compile
        run: haxelib run lime build android -${{ matrix.build }} -D no-compilation -D luajit_static -D macro-times -D analyzer-optimize -64 --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build-ubuntu${{ matrix.version }}-64-${{ matrix.build }}
          path: 'export/${{ matrix.build }}/android/bin/app/build/outputs/apk/debug/*.apk'
