name: Windows Build CI

on: [workflow_dispatch]

jobs:
  build:
    name: Windows
    runs-on: windows-${{ matrix.version }}
    strategy:
      matrix:
        arch: [32, 64]
        build: [release, debug]
        version: [2019, 2022]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install openfl-samples --quiet
          haxelib install actuate --quiet
          haxelib --never install flixel 4.11.0 --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install hscript --quiet
          haxelib install flixel-addons --quiet
          haxelib git faxe https://github.com/uhrobots/faxe.git
          haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
          haxelib git polymod https://github.com/mcagabe19/polymod-for-steve.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git
          haxelib set openfl 9.1.0
          haxelib set flixel 4.11.0
          haxelib set lime 7.9.0
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows -${{ matrix.arch }} -${{ matrix.build }} -D no-compilation -D luajit_static -D macro-times -D analyzer-optimize --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build-${{ matrix.version }}-${{ matrix.arch }}-${{ matrix.build }}
          path: export/${{ matrix.build }}/windows/bin
